# Basic Usage Demo - 2

In [4]:
import numpy as np
import tensor_utils as tu


A = np.arange(10)
print("A -> ")
print(A)
print('\n')

windows = tu.add_past_windows(A, lb=3, strict_lookback=True)
print("windows -> ")
print(windows)

A -> 
[0 1 2 3 4 5 6 7 8 9]


windows -> 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]]


## test latex $QP$

The quadratic formula is:

$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

<div align="center">
<img src="sberry.jpeg" width="300" alt="Local Image">
</div>


[Download the derivation (PDF) v1](files/test_page.pdf)
